// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARWnqKYY61CVnV5DcBM2XHqLJnUmfUdXI',
    appId: '1:532523505790:web:49bc2735ad1694f741602f',
    messagingSenderId: '532523505790',
    projectId: 'barcodescannerapp-12913',
    authDomain: 'barcodescannerapp-12913.firebaseapp.com',
    storageBucket: 'barcodescannerapp-12913.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvwIsX1bdE58X7EcjAdZc6ehNAtoJ2C1g',
    appId: '1:532523505790:android:7f1503ebbb52ca5c41602f',
    messagingSenderId: '532523505790',
    projectId: 'barcodescannerapp-12913',
    storageBucket: 'barcodescannerapp-12913.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEnNFmiuXtSoG7CUWMo94PYV-l7Qd95QM',
    appId: '1:532523505790:ios:83101c77696267fa41602f',
    messagingSenderId: '532523505790',
    projectId: 'barcodescannerapp-12913',
    storageBucket: 'barcodescannerapp-12913.appspot.com',
    iosBundleId: 'com.example.barcodeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEnNFmiuXtSoG7CUWMo94PYV-l7Qd95QM',
    appId: '1:532523505790:ios:d41f2e64b7e2b03f41602f',
    messagingSenderId: '532523505790',
    projectId: 'barcodescannerapp-12913',
    storageBucket: 'barcodescannerapp-12913.appspot.com',
    iosBundleId: 'com.example.barcodeApp.RunnerTests',
  );
}
